import 'package:bloodsage/data/models/report_parameter.dart';
import 'package:equatable/equatable.dart';
import 'package:hive/hive.dart';

part 'medical_report.g.dart'; // Will be generated by build_runner

@HiveType(typeId: 0) // Unique typeId for Hive
class MedicalReport extends Equatable {
  @HiveField(0)
  final String id; // A unique ID for each report (e.g., a timestamp or UUID)

  @HiveField(1)
  final DateTime reportDate; // The date the report was taken or uploaded

  @HiveField(2)
  final String labName; // Optional: Name of the lab (e.g., "RedCliff Labs")

  @HiveField(3)
  final List<ReportParameter>
      parameters; // The list of all results in this report

  const MedicalReport({
    required this.id,
    required this.reportDate,
    required this.parameters,
    this.labName = 'Unknown Lab',
  });

  @override
  List<Object> get props => [id, reportDate, labName, parameters];
}
